### ISSUE TITLE
macbed.com

### ISSUE THREAD

**Issue by Fezreal** [jspenguin2017/AdBlockProtector#179] opened 2017-05-05 02:40 UTC
https://www.macbed.com/download/34297.html

click any server will show a popup about against adblock
![image](https://cloud.githubusercontent.com/assets/6703674/25732221/c55fddc2-317f-11e7-860e-e8f35ead6580.png)

**Comment by jspenguin2017** [comment] 2017-05-05 03:00
Hi, I can't reproduce it. Can you post your setup? 

* Browser
* Script host
* Ad blocker
* What other extension and Userscripts you are using

**Comment by Fezreal** [comment] 2017-05-05 06:16
mac chrome 58.0.3029.96 (64-bit)
using uBlock Origin and here is my settings file
[my-ublock-backup_2017-05-05_14.15.03.txt](https://github.com/jspenguin2017/AdBlockProtector/files/978228/my-ublock-backup_2017-05-05_14.15.03.txt)

**Comment by uBlock-user** [comment] 2017-05-05 11:12
Patched by the script. If it doesn't work for you, you can use these filters below.

```
@@||macbed.com^$elemhide
macbed.com##.adsbygoogle
```

**Comment by jspenguin2017** [comment] 2017-05-05 13:12
Which script host are you using?

**Comment by Fezreal** [comment] 2017-05-05 14:01
@jspenguin2017 
<img width="481" alt="screenshot 2017-05-05 22 01 10" src="https://cloud.githubusercontent.com/assets/6703674/25748663/6ea0cb68-31de-11e7-9482-27df17ebcf48.png">

**Comment by Fezreal** [comment] 2017-05-05 14:06
@uBlock-user 
`@@||macbed.com^$elemhide
macbed.com##.adsbygoogle`
 it's worked, thanks.....

**Comment by uBlock-user** [comment] 2017-05-05 14:37
Yes, it's the filter solution, however you shouldn't need this if you're using AdBlock Protector Script as it's already patched in there. You should investigate that.

**Comment by jspenguin2017** [comment] 2017-05-05 14:47
@Fezreal 
您貌似没有安装用户脚本管理器，我们目前支持[Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?utm_source=chrome-ntp-icon)，请在插件商店中安装然后点击[这里](https://github.com/jspenguin2017/AdBlockProtector/raw/master/AdBlockProtector.user.js)来安装我们的用户脚本。

**Comment by Fezreal** [comment] 2017-05-06 00:56
@jspenguin2017  我无语了, 既然Adblock Protector List需要Tampermonkey才能用, 那uBlock干嘛把这个列表内置进去了..

**Comment by jspenguin2017** [comment] 2017-05-06 02:14
@Fezreal 我也不是很清楚，我本人并没有要求uBO的作者这样做。Anti-Adblock Killer也是这样的，需要Tampermonkey脚本才能正常运行。虽然脚本安装方法可以通过uBO控制面板中的“i”按钮查看，但是我想大部分人都不会去点。如果脚本安装说明能够更明显一点就好了……
![image](https://cloud.githubusercontent.com/assets/7283682/25769123/22dfe8b2-31cf-11e7-8358-5d28dd4de9ce.png)

**Comment by Fezreal** [comment] 2017-05-06 02:27
坐等 @gorhill

**Comment by jspenguin2017** [comment] 2017-05-11 20:14
I'm closing this since it is somewhat off topic.

**Closed by jspenguin2017** 2017-05-11 20:14 UTC
Labels: Cannot Reproduce
