### ISSUE TITLE
menshealth.pl, womenshealth.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#162] opened 2017-04-24 10:39 UTC
we found this on the webiste:

`||www.menshealth.pl/js/adb_eyeo.js$script,domain=www.menshealth.pl`

but still getting this 15 sec ad that we think is base on cookies (shows up only 1 time): 

![e96fbf88-276c-11e7-8e22-019af1d5dec9](https://cloud.githubusercontent.com/assets/15007183/25333459/43ce3738-28b8-11e7-8623-ef889f0b3301.PNG)

we were hoping you can add something like this or better to your script:

```JavaScript
if (a.domCmp(["auto-motor-i-sport.pl", "menshealth.pl", "womenshealth.pl"])) {
    a.ready(function () {
        if (a.win.location.pathname.startsWith("/welcome-page")) {
            a.$(".bgWhite.container").hide();
            a.$(".btn.btn-info")[0].click();
        };
    });
}
```

**Comment by jspenguin2017** [comment] 2017-04-24 20:04
I can't reproduce it. Do you have a test link? 
![image](https://cloud.githubusercontent.com/assets/7283682/25356172/8ecbb5b0-28f6-11e7-8af5-1f76928607a2.png)

**Comment by F4z** [comment] 2017-04-24 20:20
Clear cookies or try in incognito/private mode and click here.
![image](https://cloud.githubusercontent.com/assets/11742596/25356837/10320eb6-293c-11e7-9c2b-e5006bf233e6.png)

**Comment by uBlock-user** [comment] 2017-04-24 20:24
cannot reproduce on both domains

**Comment by F4z** [comment] 2017-04-24 20:59
I do not know why you can not reproduce this.
I can reproduce this in incognito mode.

<details><summary>GIF</summary>

![](http://i.imgur.com/DxNgj6a.gif)

</details>

**Comment by jspenguin2017** [comment] 2017-04-24 22:18
@F4z OK, I see. I think we just need to expand our solution. Thanks.

**Comment by jspenguin2017** [comment] 2017-04-24 22:52
This should be fixed now, can you test it out?

**Comment by F4z** [comment] 2017-04-24 22:59
It works, thank you.

**Comment by uBlock-user** [comment] 2017-04-25 11:09
Already patched by `/blockadblock.$script` filter from uBlock Filters, should work for you, nothing to do with Incognito Mode.

**Comment by uBlock-user** [comment] 2017-04-25 11:27
Alright I can reproduce this if I remove all cache and site data, so it's like forbes. It's cookie based.

**Comment by uBlock-user** [comment] 2017-04-25 11:28
Proper test link - http://www.womenshealth.pl/lekcja-zycia/Elsa-Pataky-gwiazda-Szybkich-i-wscieklych-i-jej-sposob-na-zyciowa-forme,8874,1

**Comment by jspenguin2017** [comment] 2017-04-27 15:37
Any feedback? Please close this issue if it works.

**Closed** 2017-04-27 15:42 UTC
Labels: Fixed
