### ISSUE TITLE
NSFW! hqporner.com

### ISSUE THREAD

**Issue by elsy04** [jspenguin2017/AdBlockProtector#189] opened 2017-05-09 19:10 UTC
Hi, a little nagging poster is always shown on all the recent videos right opening their specific pages, which tells only low quality videos will be available. 

I'm using a slightly out of standard setup:

SRWare Iron v58.0
Content settings... are left as default.
"Do Not Track" request with your browsing traffic **disabled**.

Ublock:
Adblock Protector List
Adblock Warning Removal List

Tampermonkey:

Factory settings

Reproducing the issue is quite easy, just open any of the recent videos' pages, like this one:

http://hqporner.com/hdporn/85025-Jade_Amber_interview_and_casting_sex.html

Thanks.

**Comment by uBlock-user** [comment] 2017-05-09 19:24
Can't reproduce.

**Comment by jspenguin2017** [comment] 2017-05-09 19:40
Can't reproduce neither.

**Comment by elsy04** [comment] 2017-05-09 19:44
OK, I just realized that message is being shown in a randomly basis; doing a few reloads over videos' sites, it will appear and disappear.

As far as I can see, the message will never show up right after opening a video's site, but only after doing a few reloads over them. And will keep that way thru' reloads, appearing/disappearing. 

That's not a big deal really, since it works right away and reloading the websites isn't something one would do just for the sake of it, but it is a weird issue to note.

Thanks.

**Comment by jspenguin2017** [comment] 2017-05-09 19:47
OK, I can reproduce it now...

**Comment by jspenguin2017** [comment] 2017-05-09 19:52
Code dump: https://pastebin.com/hkMSEJsG
I think this works: `a.readOnly("hasAdblock", false);`

**Comment by jspenguin2017** [comment] 2017-05-09 19:56
I pushed out a fix, update Script and let me know if it still happens.

**Comment by elsy04** [comment] 2017-05-09 19:59
I'm sorry but I'm new to this. How am I supposed to import that to test it?

Thanks.

**Comment by jspenguin2017** [comment] 2017-05-09 20:00
Oh wait... That's not right... It tries to load `http://62.212.86.9/js/ads.js` which returns: 
`var canRunAds = true;`
But that variable should have been patched. Looks like it's race condition, we have to patch it with a filter.

**Comment by jspenguin2017** [comment] 2017-05-09 20:12
I think this rule works: `@@|http://62.212.86.9/js/ads.js|$domain=mydaddy.cc`
It's not ideal, but I guess we don't have an option until I learn how to code WebExtension.

**Comment by elsy04** [comment] 2017-05-09 20:36
OK, that rule does the job.

By the way, the only way I found to getting rid of that message so far was using Firefox and uBlock (no ABP) with similar settings, by allowing third-party scripts for that full website. But now, I realized that with only that rule the message will not bother anymore, and still blocking 3rd p scripts.

http://i.imgur.com/xMsKgLq.jpg

Thanks again.

**Comment by uBlock-user** [comment] 2017-05-10 11:17
I cannot reproduce no matter how many videos I browse or how many time I refresh the page.

**Comment by jspenguin2017** [comment] 2017-05-11 20:12
Since this issue is fixed, I'll close it now.

**Closed by jspenguin2017** 2017-05-11 20:12 UTC
Labels: Fixed
