### ISSUE TITLE
keshavcommoditycalls.com

### ISSUE THREAD

**Issue by manjusr81** [jspenguin2017/AdBlockProtector#213] opened 2017-05-18 06:00 UTC
http://keshavcommoditycalls.com/running-calls/

Pls find the attachments
rgds
![selection_043](https://cloud.githubusercontent.com/assets/9315238/26188534/51e638b2-3bbd-11e7-81ae-6b5c2b461b9e.png)
![selection_042](https://cloud.githubusercontent.com/assets/9315238/26188541/5c058cda-3bbd-11e7-99fa-03ce26aef3be.png)

**Comment by uBlock-user** [comment] 2017-05-18 11:36
Can't reproduce.

**Comment by manjusr81** [comment] 2017-05-18 11:44
Can u pls be clear Sir.

Rgds

**Comment by jspenguin2017** [comment] 2017-05-18 15:25
Can't reproduce.

**Comment by jspenguin2017** [comment] 2017-05-18 15:31
![image](https://cloud.githubusercontent.com/assets/7283682/26210423/c481f28c-3bac-11e7-9dda-193864077cd5.png)

**Comment by ghajini** [comment] 2017-05-18 15:34
Hi @manjusr81 keep only ublock origin(with adblock protector list enabled then click purge all caches and then update all) and 
tampermonkey(adprotector script installed and updated to latest)....

Disable all extensions......o

Or create new chrome profile(Google how to create new chrome profile) with ublock origin and tampermonkey (with adblock protector script)

**Comment by manjusr81** [comment] 2017-05-18 15:41
Thanks a lot.  will try and get back to u.

rgds
Manjunath

**Comment by jspenguin2017** [comment] 2017-05-23 03:43
Closing since I still can't reproduce it.

**Closed by jspenguin2017** 2017-05-23 03:43 UTC
Labels: Cannot Reproduce
