### ISSUE TITLE
mexashare.com

### ISSUE THREAD

**Issue by Reoldyk** [jspenguin2017/AdBlockProtector#217] opened 2017-05-19 02:18 UTC
![untitled](https://cloud.githubusercontent.com/assets/4547317/26230552/fb3c1164-3c73-11e7-89fd-b6e398ce5f06.png)

test link = http://www.mexashare.com/6h5qwjm1j4ez/Tate_no_Yusha_no_Nariagari_v05-08.rar

FF 51.0.1
Ublock origin 1.12.4

**Comment by jspenguin2017** [comment] 2017-05-19 02:55
Can't reproduce block screen. I will try to remove the countdown.

**Comment by jspenguin2017** [comment] 2017-05-19 04:00
NVM, the countdown is enforced on server side... 
![image](https://cloud.githubusercontent.com/assets/7283682/26232707/5ec82bf0-3c15-11e7-961d-6ede9d91cd0e.png)
This can skip countdown but it's kind of pointless... 
```JavaScript
if (a.domCmp(["mexashare.com"])) {
    a.timewarp("setTimeout", a.matchMethod.stringExact, "1000");
}
```

**Comment by jspenguin2017** [comment] 2017-05-19 04:01
Basically if the countdown function is like this, 9 times out of 10, it can't be skipped. 
![image](https://cloud.githubusercontent.com/assets/7283682/26232743/8acbf0e2-3c15-11e7-82f5-94bf0b784b47.png)

**Comment by jspenguin2017** [comment] 2017-05-19 04:08
Looks like it is caught in our generic solutions. Go properly install Script and try again. 
![image](https://cloud.githubusercontent.com/assets/7283682/26232862/68fae1c0-3c16-11e7-9ad4-d887f17a84e2.png)
Also, I added a Script rule that removes the popup.

**Comment by uBlock-user** [comment] 2017-05-19 09:45
Can't reproduce.

Timer remains even after I updated to the latest version of the Script.

**Comment by jspenguin2017** [comment] 2017-05-19 15:01
@uBlock-user As I said before, the timer is enforced on server side.

**Comment by uBlock-user** [comment] 2017-05-19 15:46
@jspenguin2017 so there's nothing we can do about it ?

I can reproduce the issue only if I disable the Script. So the domain is patched.

**Comment by jspenguin2017** [comment] 2017-05-19 17:13
@uBlock-user If it is properly implemented on the server side, then there is nothing we can do about it. If you want to dig deeper, feel free to do that. 
The ad blocker detection part is caught in our generic solutions.

**Comment by jspenguin2017** [comment] 2017-05-20 17:12
I just tested again and it's still working. So I'm closing this issue, let me know if there are other problems.

**Closed by jspenguin2017** 2017-05-20 17:12 UTC
Labels: Cannot Reproduce
