### ISSUE TITLE
flashx.tv (iframe of filmy.to)

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/AdBlockProtector#130] opened 2017-04-04 00:04 UTC
test link:

~~http://filmy.to/film/Pitbull_Niebezpieczne_kobiety-2016,19812~~
Update from jspenguin2017: The old test link is no longer working, this is the new test link: 
http://filmy.to/film/Podroz_na_Ksiezyc-1902,230933

![capture](https://cloud.githubusercontent.com/assets/15007183/24636497/b468a1ec-18a8-11e7-9cf8-2b0c1f1ebdbe.PNG)

**Comment by X01X012013** [comment] 2017-04-04 00:16
OK, I'll have a look.

**Comment by uBlock-user** [comment] 2017-04-04 09:31
That's the iframe of flashx.tv

**Comment by uBlock-user** [comment] 2017-04-04 13:52
an fyi flashx.tv is broken - https://github.com/uBlockOrigin/uAssets/issues/294

**Comment by X01X012013** [comment] 2017-04-04 13:56
I was wondering why the player isn't working yesterday... And I thought some filters broke it. Does it not work with uBO off?

**Comment by uBlock-user** [comment] 2017-04-04 13:57
I don't know, my solution used to work, but the website is beyond broken now, as reported even after turning uBO off sometimes it won't work. The webmaster messed it up pretty badly. I gave up on this one.

**Comment by uBlock-user** [comment] 2017-04-06 13:57
The link has gone 404, new test-case - https://www.flashx.tv/431e404f05071433e21fff787b174d61.jsp

**Comment by uBlock-user** [comment] 2017-04-06 14:04
Try  - `a.noAccess("jQuery.adblock");`

I can see the player now - https://i.gyazo.com/eadf7cfa96ec895504a690b4435a6809.png

**Comment by uBlock-user** [comment] 2017-04-06 14:11
popups for still an issue though, even after blocking all scripts they're still induced.

**Comment by uBlock-user** [comment] 2017-04-06 14:34
@X01X012013 Offtopic Q - Would you be interested in patching 100+ newspaper websites running the same anti adblock script if I present with the solution ?

**Comment by X01X012013** [comment] 2017-04-06 15:29
@uBlock-user Open a new issue, I'll have a look.

**Comment by X01X012013** [comment] 2017-04-06 15:30
Also, I don't think `a.noAccess` can change `jQuery` on `document-start`, it will probably throw an error and do nothing.

**Comment by uBlock-user** [comment] 2017-04-06 15:35
That's the solution I have used from the beginning and has worked sometimes and sometimes not because the website is broken. 

As luck would have it locking that variable is working today.

**Comment by X01X012013** [comment] 2017-04-06 15:51
If you run `a.noAccess("jQuery.adblock");` on `document-start`, I am 99.99% sure that it will print an error in console and do nothing. The internal error that is caught is probably undefined is not an object or something. 
If it sometimes work sometimes don't, then it's something else.

**Comment by uBlock-user** [comment] 2017-04-06 16:08
> it will print an error in console (if in debug mode) and do nothing
https://i.gyazo.com/31c2f8af1bdf73d9ac800648b0dbc2eb.png

Nothing of that sort, I set the level to verbose, warnings, errors, nothing there.

**Comment by uBlock-user** [comment] 2017-04-06 16:27
This site is very nasty, it's blocking right click context menu, console(F12 has no effect) and runs a timer too.

**Comment by xxcriticxx** [comment] 2017-04-06 16:29
pl site or flashx?

**Comment by X01X012013** [comment] 2017-04-06 16:29
Short answer: 
It's a bit complex, if the part before `.` is not a built-in property, then it doesn't work. 

Long answer: 
This is the implementation of `a.noAccess`: 
https://github.com/X01X012013/AdBlockProtector/blob/master/Script%20Compiler/Core.js#L609
`a.noAccess` will try to define a property to `a.win["jQuery"]`, but that is undefined, which is not an object. `a.win.Object.defineProperty` only works on objects, so it throws an error which is internally caught by `a.noAccess`. 
Even if you define `jQuery` before calling `a.noAccess`, that would still not work, since the real jQuery will completely replace the `jQuery` that you defined. If you make `jQuery` not replaceable, then chances are the website would not work at all. So the `jQuery` you define must be a real jQuery, which is tricky to get.

**Comment by uBlock-user** [comment] 2017-04-09 15:01
That should kill popups and timer, see if it works as intended

```javascript
if (a.domCmp(["flashx.tv"])) {
    a.readOnly("OpenInNewTab", function ( ) { });
    a.readOnly("countdown", function ( ) { });
    a.noAccess("r3D");
    a.win.eval = function ( ) { };
    a.filter("setTimeout", "countdown");
    a.filter("document.addEventListener", /^contextmenu$/);
}  
```

**Comment by X01X012013** [comment] 2017-04-09 17:03
`a.filter` only takes in RegExp as 2nd argument, passing string would crash the handler.

**Comment by X01X012013** [comment] 2017-04-09 17:06
The original test link is returning 404, so I tested on this link: http://filmy.to/film/Ksiadz-2017,241476
Seems to work. Adding to Script. Thanks.

**Comment by X01X012013** [comment] 2017-04-09 17:09
The original link is returning 404, I tried this link: http://filmy.to/film/Podroz_na_Ksiezyc-1902,230933
Popup is not killed, right click is working...

**Comment by X01X012013** [comment] 2017-04-09 17:18
This fixes popup. 
```JavaScript
if (a.domCmp(["filmy.to", "histock.info"])) {
    a.win.open = function () {
        return { closed: false };
    };
}
```

**Comment by uBlock-user** [comment] 2017-04-09 17:46
> The original link is returning 404, I tried this link: http://filmy.to/film/Podroz_na_Ksiezyc-1902,230933

Yes, I mentioned that with a new link 3 days ago 
 - https://github.com/X01X012013/AdBlockProtector/issues/130#issuecomment-292182514

> Popup is not killed

I cannot reproduce popups anymore on `flashx.tv` even after removing all site data and cookies

**Comment by uBlock-user** [comment] 2017-04-09 17:48
Anti adblock is still there, other than that everything looks fine.

**Comment by uBlock-user** [comment] 2017-04-09 18:03
Nevermind, the website is down now.

**Comment by X01X012013** [comment] 2017-04-09 18:16
It still works for me... 
![image](https://cloud.githubusercontent.com/assets/7283682/24839797/6306be72-1d1e-11e7-9705-986234fe7e33.png)

**Comment by uBlock-user** [comment] 2017-04-09 18:37
Does that big blue button work when you click on it ?

**Comment by uBlock-user** [comment] 2017-04-09 18:43
Need to block `flashx.tv/checkembed.php?c=497xzrf4805i`

**Comment by uBlock-user** [comment] 2017-04-09 18:45
Check this out - https://www.flashx.tv/js/code.js

**Comment by X01X012013** [comment] 2017-04-09 20:38
Well, the button "works", it sends me to the "ad block detected" page...

**Comment by X01X012013** [comment] 2017-04-09 20:41
This is the code from that blue button iframe: 
```JavaScript
function s(m) {
    var w = window;
    while (w != window.top) {
        w = w.parent;
        try {
            w.postMessage(m, "*");
        } catch (e) {}
    }
}
s('l', "*");

function go() {
    var nw = window.open("https://histock.info/aUg3RUQIKlQ3e088XiF5X3sEdndZbkUgIFR5ESQmHXUGYzJUeRl0dEd9Dmt1WW5CeHBcewJ0IFopDncgXClScCEPe1YncQx+B3x8XnxRI30MblE2eVhuXiN5WW5EKHlafBEueU86UiN5ATxDNTdMe3Zgdi9tBQMzHj8ZIygIO189ah0+EncCDCVVICBHOF81YVoOVGB3LXwOcjwTOlFxfFl9XmMnHXUHYycdKwp1Yho8RHh1TydEN3kPIVsoPUc8WGM0GyYKdWI");
    s((nw && nw.closed == false) ? 'o' : 'c', "*")
}
```
Looks like it is posting some message to the main window...

**Comment by X01X012013** [comment] 2017-04-09 20:48
> Check this out - https://www.flashx.tv/js/code.js

Hum... We can just block this file...

**Comment by X01X012013** [comment] 2017-04-09 21:18
Well, the obvious thing to do is to white list flashx1.tv/js/showadcode.js

**Comment by X01X012013** [comment] 2017-04-09 21:25
Hum... For some reason, I can't override this rule from EasyList... 
![image](https://cloud.githubusercontent.com/assets/7283682/24841088/c96cd7ea-1d38-11e7-9260-8cf3b122ce32.png)

**Comment by uBlock-user** [comment] 2017-04-09 22:04
Those are already whitelisted by Adguard and it still doesn't help

**Comment by uBlock-user** [comment] 2017-04-09 22:06
> it sends me to the "ad block detected" page...

Yes I'm facing that too and it can be stopped by blocking `flashx.tv/checkembed.php`

**Comment by X01X012013** [comment] 2017-04-09 22:42
OK, the newest patch should properly fix context menu and dev tools shortcut keys. 
The player is still not working though, it redirects me to another block screen.

**Comment by uBlock-user** [comment] 2017-04-09 23:02
Surprisingly, it's working fine for me and the anti adblock no longer ensues, test link - https://www.flashx.tv/ce29bccbe0232d2bad7b41db122ed5f7.jsp

Probably because Adguard's English filter whitelisted quite a bit to make it working

```
@@||flashx.to/counter.cgi
@@||*/jquery2.js$third-party,domain=flashx.tv
||static.flashx.tv/js/flashx.js
||static.flashx.tv/img/fx.png

```

**Comment by X01X012013** [comment] 2017-04-09 23:30
Nope, doesn't work for me. 
![image](https://cloud.githubusercontent.com/assets/7283682/24841822/35b7e37a-1d4a-11e7-96d7-77d46bbe17ac.png)

**Comment by xxcriticxx** [comment] 2017-04-10 01:13
not working 

![screenshot from 2017-04-09 21-12-05](https://cloud.githubusercontent.com/assets/15007183/24842714/6278e00c-1d69-11e7-9ca5-37547037d653.png)

**Comment by X01X012013** [comment] 2017-04-10 01:32
@xxcriticxx We are still working on this.

**Comment by uBlock-user** [comment] 2017-04-10 05:55
Alright just for the sake of experimentation would you subscribe to Adguard English Filter and then try again ?

**Comment by xxcriticxx** [comment] 2017-04-10 11:06
@uBlock-user i cant get pass this i click on proceed to video and nothing happens 

![capture](https://cloud.githubusercontent.com/assets/15007183/24858899/3207483e-1dbc-11e7-9fac-8c6bfc9db67d.PNG)

**Comment by uBlock-user** [comment] 2017-04-10 12:42
@xxcriticxx link - https://www.flashx.tv/148f1181367c11ae6fd27b073039176b.jsp

Works fine for me - https://i.gyazo.com/33ada85abd34b70c34288bfd0b2c4fc9.png

**Comment by X01X012013** [comment] 2017-04-10 13:55
@uBlock-user Do you know which rules from that filter list is having effect?

**Comment by uBlock-user** [comment] 2017-04-10 14:29
Probably all whitelisting rules for the domain `flashx.tv`

**Comment by uBlock-user** [comment] 2017-04-10 14:39
Try these 

```
@@||flashx1.tv/sidead.js
@@/js/showad*.js$domain=flashx.tv|flashx.to
@@||flashx1.tv/js/showadcode.js
@@||*/jquery2.js$domain=flashx.tv,third-party
@@||*/js/showad_.js$domain=flashx.tv
@@||flashx.tv/counter.cgi$domain=flashx.tv
@@||flashx.to/counter.cgi
||static.flashx.tv/img/fx.png
||static.flashx.tv/img/downloadit.png
||static.flashx.tv/js/flashx.js
flashx.tv##a[href^="http://www.flashx.tv/downloadthis"]
||flashx.tv/img/downloadit.png
@@||fastcontentdelivery.com^$script,domain=flashx.tv
@@||flash-x.tv/js/showad$script
@@||flashx.tv/js/jquery.cookie.js
@@||flashx.tv/js/jquery.min.js|
@@||flashx.tv/js/light.min.js|
@@||flashx.tv/js/showad$script
@@||flashx.tv/js/xfs.js
@@||flashx.tv/js/xupload.js
@@||flashx.tv/player6/jwplayer.js
|http://$script,third-party,xmlhttprequest,domain=flash-x.tv|flashsx.tv|flashx.me|flashx.run|flashx.tv|flashx1.tv|flashxx.tv
|https://$script,third-party,xmlhttprequest,domain=flash-x.tv|flashsx.tv|flashx.me|flashx.run|flashx.tv|flashx1.tv|flashxx.tv
@@||flashx.$generichide
@@||flashx.tv/js/ad*.js$script
```

**Comment by xxcriticxx** [comment] 2017-04-10 15:02
@uBlock-user yes i added adguard english filters

**Comment by xxcriticxx** [comment] 2017-04-10 15:05
@uBlock-user works after i clear my history and cookies 

![capture](https://cloud.githubusercontent.com/assets/15007183/24868272/89252232-1ddd-11e7-9bad-9c58a84a6ce1.PNG)

**Comment by X01X012013** [comment] 2017-04-10 15:17
@uBlock-user @xxcriticxx Thanks. I'll check it out.

**Comment by uBlock-user** [comment] 2017-04-10 15:28
@X01X012013 you can fix it via the Script, whitelisting is the only choice now.

**Comment by X01X012013** [comment] 2017-04-10 16:01
@uBlock-user As long as it doesn't let real ads in, it's fine.

**Comment by xxcriticxx** [comment] 2017-04-10 16:21
@uBlock-user adding adgard english filters did the trick no need to whitelist

**Comment by uBlock-user** [comment] 2017-04-10 16:25
@X01X012013 Ofcourse not, no ads are coming in, but can you take care of the timer ?

@xxcriticxx Did you add the Adguard English Filter or the filters I posted here ? It doesn't make a difference they both whitelist, I took those filters from that list itself.

**Comment by xxcriticxx** [comment] 2017-04-10 16:29
@uBlock-user i added whole adguard english list

**Comment by uBlock-user** [comment] 2017-04-10 16:32
Yeah that will do the job too, I did the same.

**Comment by xxcriticxx** [comment] 2017-04-10 16:34
that list is some type of enhance easylist version

**Comment by jspenguin2017** [comment] 2017-04-24 19:49
Sorry I was a bit busy lately... So for this test link: http://filmy.to/film/Podroz_na_Ksiezyc-1902,230933
the rules @uBlock-user posted above don't seem to work...

**Comment by uBlock-user** [comment] 2017-04-24 20:37
@jspenguin2017 

![](https://i.gyazo.com/08d27472531329198fe2357da4c42a8c.png)

**Comment by jspenguin2017** [comment] 2017-04-24 22:17
Hum... Interesting... it somehow doesn't work for me... I'll investigate later.

**Comment by xxcriticxx** [comment] 2017-04-25 00:30
still works 

![capture](https://cloud.githubusercontent.com/assets/15007183/25363966/e65b35f4-292c-11e7-8cdf-37936cb1771e.PNG)

**Comment by jspenguin2017** [comment] 2017-04-25 00:50
Hum... I need to figure out which filter in Adguard does the magic...

**Comment by xxcriticxx** [comment] 2017-04-25 01:21
Up to you man your the owner of this project

**Comment by uBlock-user** [comment] 2017-04-25 14:03
> Or maybe we should switch recommended setup over?

What does that mean ?

**Comment by jspenguin2017** [comment] 2017-04-25 14:20
@uBlock-user I mean from standard EasyList to Adguard EasyList.

**Comment by uBlock-user** [comment] 2017-04-25 14:52
Adguard's English Filter is derivative of Easylist and contains the same rules in addition to their own, nothing more, nothing less.

**Comment by xxcriticxx** [comment] 2017-04-25 15:02
! Title: Adguard English Filter.
!
! Filter that enables removing of the ads from websites with English content.
! Originally based on the EasyList filter (https://easylist.adblockplus.org/).
! Modified by Adguard team according to the complaints from users.

**Comment by jspenguin2017** [comment] 2017-04-25 15:04
@xxcriticxx It removes bad white listing, exactly what we want.

**Comment by xxcriticxx** [comment] 2017-04-25 15:51
looking on it it has 6000 different filters then easylist

**Comment by uBlock-user** [comment] 2017-04-25 16:43
It has many bad whitelisted filters copied from Easylist, so I had to `$badfilter` them all, fyi

**Comment by xxcriticxx** [comment] 2017-04-25 16:51
@jspenguin2017 maybe with @uBlock-user help you can make list here what you think?

**Comment by jspenguin2017** [comment] 2017-04-25 16:58
@xxcriticxx 
Please no, that would be a bit too much work, it has over 72k entries. There are no reasonable way for us to clean that mess up...

**Comment by xxcriticxx** [comment] 2017-04-25 17:25
@jspenguin2017 
well maybe we can use/run @uBlock-user badfilter list?

**Comment by uBlock-user** [comment] 2017-04-26 10:46
Mine isn't complete and isn't related to this domain in context, so that would be pointless.

**Comment by jspenguin2017** [comment] 2017-05-12 02:09
I don't think we should make the Adguard filter as the standard setup since it contains a lot of script rules. I can't seem to get this one working. If Adguard filter is the magic bullet that somehow fixes this issue, then we can mark that as a workaround.

**Comment by ghajini** [comment] 2017-05-15 01:12
Its working finely in Firefox herein, can anyone check that...
Link-
`http://filmy.to/film/Podroz_na_Ksiezyc-1902,230933`

**Comment by jspenguin2017** [comment] 2017-05-15 01:42
The website is still usable since you can just pick another source... 
![image](https://cloud.githubusercontent.com/assets/7283682/26039932/73f5fdd0-38dd-11e7-8a7a-a9190df0b28c.png)

**Comment by ghajini** [comment] 2017-05-15 13:46
Add tag of `site broken` instead of `currently no solution `.....flashx.TV is normal here

**Comment by ghajini** [comment] 2017-05-15 13:58
It shows antiadblock message when visit that several times,so might be it has some code which detects that visits......

**Comment by xxcriticxx** [comment] 2017-05-15 14:13
works with adguard filters. flashx opens like 4 popups website when you push play button

![capture](https://cloud.githubusercontent.com/assets/15007183/26061840/130c687c-3957-11e7-8b36-4a0260b52f69.PNG)

**Comment by ghajini** [comment] 2017-05-21 15:37
@jspenguin2017 
Easylist filters might have broken site(site functioning).........
How these code help us
https://github.com/AdguardTeam/AdguardFilters/search?utf8=%E2%9C%93&q=flashx&ty

**Comment by lain566** [comment] 2017-05-22 18:05
@jspenguin2017 Why is there no solution to this issue?

**Comment by jspenguin2017** [comment] 2017-05-22 18:25
@lain566 I could not extract the filters that does the magic...

**Comment by lain566** [comment] 2017-05-22 18:28
@jspenguin2017  Try these

```
@@||flashx1.tv/js/showad*.js$script
@@||flashx1.tv/sidead.js$script
@@||flashx.to/counter.cgi$script
@@||flashx1.tv/jquery2.js$script

||static.flashx.tv/js/flashx.js$script
@@||somethodox.info/popunder.gif$xmlhttprequest,domain=flashx.tv
||somethodox.info/?&subid=*&pid=*&tid=*$beacon,image,domain=flashx.tv
```

**Comment by jspenguin2017** [comment] 2017-05-22 18:30
@lain566 Oh WOW! Well done 😄 Thanks.

**Comment by lain566** [comment] 2017-05-22 18:39
@jspenguin2017 You're welcome :grin:

**Comment by jspenguin2017** [comment] 2017-05-23 16:48
Looks like it's still working. Closing.

**Closed by jspenguin2017** 2017-05-23 16:48 UTC
Labels: Fixed

**Comment by lain566** [comment] 2017-06-30 19:49
@jspenguin2017  The site has changed

remove this rules
```
@@||somethodox.info/popunder.gif$xmlhttprequest,domain=flashx.tv
||somethodox.info/?&subid=*&pid=*&tid=*$beacon,image,domain=flashx.tv
```


add this rules to prevent popups
`@@||/popunder.gif$xmlhttprequest,domain=flashx.tv`
```
a.cookie("noprpaylqckrpuwntcnt", "1");
a.cookie("noprpaylqckrpuwntexp", "1");
```


Fake video player is a bait to its ad page, appears when the video file does not exist
`||static.flashx.tv/img/player.png$image`
https://www.flashx.tv/431e404f05071433e21fff787b174d61.jsp

**Comment by jspenguin2017** [comment] 2017-06-30 20:00
Updated. Thanks. 

New test link: https://www.flashx.tv/a476a788d8fb15cd98b6ee992982f5f0.jsp

**Comment by lain566** [comment] 2017-06-30 20:13
@jspenguin2017 Cool! Thanks to you!

**Comment by uBlock-user** [comment] 2017-06-30 20:51
Add - 

```
||alikelys.com^$third-party
flashx.tv##a[href^="https://adsrvmedia.adk2x.com"]
```

**Comment by jspenguin2017** [comment] 2017-06-30 20:57
What the first two lines do?

**Comment by lain566** [comment] 2017-07-05 22:11
@jspenguin2017  The site changed its player by [Video JS](http://videojs.com/getting-started/#download-cdn)
now it's broken by easylist rule

suggested filter
`@@||zencdn.net^$script,domain=flashx.tv`

or `badfilter` I don't know if it will be a good idea

test link
http://flashx.tv/di8jfr1runee.html
http://www.mywatchseries.ac/link/flashx.tv/15089458

**Comment by jspenguin2017** [comment] 2017-07-05 23:15
Looks like it is using random domain names, block all except whitelist is the way to go.

**Comment by lain566** [comment] 2017-09-07 09:15
@jspenguin2017 uBlock Protector Extension is blocking embedded playback
Disabling uBlock Protector Extension, the flashx playback is back to normal.

Test link:
http://www.mewatchseries.to/link/flashx.tv/15368653

**Comment by jspenguin2017** [comment] 2017-09-07 22:35
Side effect of the popup blocking logic... The rule is outdated, I'll remove it for now.

**Comment by jspenguin2017** [comment] 2017-09-07 22:41
This should fix it.

**Comment by lain566** [comment] 2017-09-25 14:28
@jspenguin2017 It's broken, they changed again.

Suggested filter
`@@||flashx.tv/counter.cgi$script`

<details><summary>Screenshot</summary>

![watch_online_stream_starship_troopers_traitor_mars_2017-09-25_13-46-07](https://user-images.githubusercontent.com/27441315/30807035-6a73a9ae-a1f8-11e7-9478-bad7892425ec.png)
</details>

--------------------------------------------------------------------------

for `flashx.to`
```
@@/showad_.js$script,domain=flashx.to
flashx.to##script:inject(abort-on-property-read.js, open)
```

**Comment by jspenguin2017** [comment] 2017-09-25 15:17
OK, I'll have a look.

**Comment by lain566** [comment] 2017-09-26 18:58
@jspenguin2017 I forgot to tell you, add it here too

https://github.com/jspenguin2017/uBlockProtector/blob/2d561272d3389e31d20206412d539fb1c5f09864/Extension%20Compiler/Extension/content/3-content-rules-1-common.js#L92

https://github.com/jspenguin2017/uBlockProtector/blob/252e32132560e6d58e6c8e356b3f5fa199c6c2e8/Extension%20Compiler/Extension/content/3-content-rules-2-specific.js#L3371
