### ISSUE TITLE
appdrop.net

### ISSUE THREAD

**Issue by Fezreal** [jspenguin2017/AdBlockProtector#216] opened 2017-05-19 01:59 UTC
~~https://appdrop.net/download~~
https://appdrop.net/is2hlh3a2pd7

![image](https://cloud.githubusercontent.com/assets/6703674/26230217/c53b8b20-3c79-11e7-9f20-2b782a71eb51.png)

**Comment by jspenguin2017** [comment] 2017-05-19 02:57
Can't quite reproduce this... I guess `bab-defuser.js` would work... 
Can someone come test this?

**Comment by jspenguin2017** [comment] 2017-05-19 03:00
I can see the BAB code, but it doesn't do anything on my device, how long does it take to show the block screen?

**Comment by Fezreal** [comment] 2017-05-19 03:40
@jspenguin2017 
https://appdrop.net/is2hlh3a2pd7
进去之后点free download, 进去之后, 点一下
![image](https://cloud.githubusercontent.com/assets/6703674/26232311/00329a08-3c88-11e7-8e7a-bec8d6df13ce.png)
立刻会弹出

**Comment by jspenguin2017** [comment] 2017-05-19 03:56
@Fezreal 更新一下规则列表，我这边测试好使。读秒跳不了，服务器那边验证。

Fixed with uBO rule. 
Can't skip countdown, enforced by server.

**Comment by Dibbyo456** [comment] 2017-05-19 04:47
@jspenguin2017 What's the patch?

**Comment by jspenguin2017** [comment] 2017-05-19 04:58
@Dibbyo456 It is added to List, it should work if you just update it.

**Comment by uBlock-user** [comment] 2017-05-19 09:36
`appdrop.net##script:inject(noeval.js)` also works as an alternative solution.

**Comment by jspenguin2017** [comment] 2017-05-20 16:59
Looks like it is still working. Closing. Let me know if something breaks.

**Closed by jspenguin2017** 2017-05-20 16:59 UTC
Labels: Fixed
