### ISSUE TITLE
comicallyincorrect.com

### ISSUE THREAD

**Issue by Phlipout** [jspenguin2017/AdBlockProtector#212] opened 2017-05-17 07:21 UTC
http://comicallyincorrect.com/2017/05/14/mothers-day-2017/

Image is hidden with adblocking enabled.  

setup deviates from standard with Stylish extension addition, and these enabled filters:

![screen shot 2017-05-17 at 12 20 41 am](https://cloud.githubusercontent.com/assets/28744287/26142723/b352822c-3a96-11e7-9130-6c349efdfe4d.png)

**Comment by uBlock-user** [comment] 2017-05-17 12:58
Filter - `@@||comicallyincorrect.com^$elemhide`

**Comment by jspenguin2017** [comment] 2017-05-17 14:47
Which rule is breaking this?

**Comment by uBlock-user** [comment] 2017-05-17 14:59
Don't know I haven't bothered to check by disabling insertion of `146` generic classes.

**Comment by jspenguin2017** [comment] 2017-05-17 15:15
The image doesn't really have anything that can be caught in a generic filter...

**Comment by uBlock-user** [comment] 2017-05-17 15:27
On my end the anti adblock script only notifies at the top and is not blocking or disrupting anything.

**Comment by jspenguin2017** [comment] 2017-05-17 15:31
Something here is broken: 
![image](https://cloud.githubusercontent.com/assets/7283682/26162307/9c5e2650-3ae3-11e7-9bf2-122889c2d6fb.png)
I'll just use `elemhide`... Thanks...

**Comment by jspenguin2017** [comment] 2017-05-17 15:32
Wait, `elemhide` doesn't help with CSS rules, so the image is still hidden...

**Comment by lain566** [comment] 2017-05-17 15:33
@jspenguin2017  `http://comicincorrect.wpengine.netdna-cdn.com/`

![ublock _ _registro_de_peticiones_de_red_-_google_c_2017-05-17_17-30-36](https://cloud.githubusercontent.com/assets/27441315/26162315/ac4b1972-3b26-11e7-951b-5552caeea9f1.png)

**Comment by jspenguin2017** [comment] 2017-05-17 15:34
@lain566 OK, I see, looks like there is a CSS rule AND a network rule that are broken.

**Comment by jspenguin2017** [comment] 2017-05-17 15:42
Looks like everything that should be blocked are blocked, but current rules are blocking too much. 

<details>

![image](https://cloud.githubusercontent.com/assets/7283682/26162688/a96b1e60-3ae4-11e7-80bd-9d00387a3779.png)
![image](https://cloud.githubusercontent.com/assets/7283682/26162723/bfbc9b1c-3ae4-11e7-83b1-df62be9b65d2.png)
![image](https://cloud.githubusercontent.com/assets/7283682/26162781/e71ba48c-3ae4-11e7-815f-3b80d512136f.png)
![image](https://cloud.githubusercontent.com/assets/7283682/26162812/fe9f52a2-3ae4-11e7-8535-8bbeff4c672c.png)

</details>

**Comment by jspenguin2017** [comment] 2017-05-17 15:43
`@@||comicallyincorrect.com^$elemhide` Hides the banner, but that's the last thing we are worry about.

**Comment by uBlock-user** [comment] 2017-05-17 16:49
What's the issue ? I don't see any images being blocked on my end.

**Comment by jspenguin2017** [comment] 2017-05-17 16:58
@uBlock-user Can you show a screenshot?

**Comment by uBlock-user** [comment] 2017-05-17 17:23
![](https://i.gyazo.com/c724d0ba2c3bafec6bbb5e60251b4d12.png)

**Comment by jspenguin2017** [comment] 2017-05-17 18:41
@uBlock-user Have a look at the expected page here: https://github.com/jspenguin2017/AdBlockProtector/issues/212#issuecomment-302131768
Red part are ads and should be blocked, but blue part are expected to show.

**Comment by uBlock-user** [comment] 2017-05-19 13:19
Ah yes, those nasty ads, probably Yavli shit.

**Comment by uBlock-user** [comment] 2017-05-19 13:28
This looks to be the script fetching nasty ads - https://gist.githubusercontent.com/uBlock-user/aca236c1f4fd24ca7cc702a5940209da/raw/08d092e9adb8e4f8ba7fd4651acf21f8d4cf855c/gistfile1.txt

**Comment by uBlock-user** [comment] 2017-05-19 13:37
Filter - `comicallyincorrect.com##script:inject(abort-on-property-read.js, MutationObserver)` kills those nasty ads but creates an error in the console 

```
VM42:1 Error running script: AdBlock Protector Script
ReferenceError: ljvmby9
ljvmby9
u @ VM42:1
```

**Comment by jspenguin2017** [comment] 2017-05-19 14:46
@uBlock-user It's about current rules blocking too much, the ads are blocked when uBO is active, but most of the blue part don't show.

**Comment by jspenguin2017** [comment] 2017-05-19 14:50
For the images to show, we have to white list `@@||comicincorrect.wpengine.netdna-cdn.com/wp-content/uploads/*`
But then there are first party sponsored content: 
![image](https://cloud.githubusercontent.com/assets/7283682/26253299/1f403b7a-3c70-11e7-8f16-1bab6d123a10.png)
I guess we can use a script rule to blow it up.

**Comment by jspenguin2017** [comment] 2017-05-19 15:03
OK, this is fixed by a combination of uBO rule and Script rule.

**Comment by uBlock-user** [comment] 2017-05-19 15:16
On my end, everything is working fine, nothing is blocked that shouldn't be blocked, except for those nasty Yavli ads, which can killed by the filter, however the `MutationObserver` is also being used by the Script, so the error on the console appears.

**Comment by jspenguin2017** [comment] 2017-05-19 15:20
@uBlock-user Those sponsored content is taken care by a Script rule.

**Comment by okiehsch** [comment] 2017-05-19 18:29
@uBlock-user I can reproduce, `comicallyincorrect.com##script:inject(abort-on-property-write.js, oio)`
works for me.

**Comment by jspenguin2017** [comment] 2017-05-19 18:58
@okiehsch I think those variable names will change from time to time...

**Comment by okiehsch** [comment] 2017-05-19 19:08
Probably true, I looked at a few `yavli` sites and right now all of them use `oio` but they can change that easily enough.

**Comment by jspenguin2017** [comment] 2017-05-20 16:49
Looks like this website is still working nicely with our fix. Closing. Let me know if something is not right.

**Closed by jspenguin2017** 2017-05-20 16:49 UTC
Labels: Fixed
