### ISSUE TITLE
linternaute.com

### ISSUE THREAD

**Issue by Slowerzs** [jspenguin2017/AdBlockProtector#224] opened 2017-05-21 14:59 UTC
Hello, it is not working on : 
http://www.linternaute.com/actualite/politique/1357555-election-presidentielle-2017-resultat-macron-lepen-2eme-tour-direct/
Thanks

**Comment by uBlock-user** [comment] 2017-05-21 15:23
Can't reproduce.

**Comment by xxcriticxx** [comment] 2017-05-21 15:26
same here

**Comment by Slowerzs** [comment] 2017-05-21 15:56
With uBlock : 
![with](https://cloud.githubusercontent.com/assets/28687818/26285376/d1afa216-3e4e-11e7-96ad-4c7a1200a5b6.png)
Without
![without](https://cloud.githubusercontent.com/assets/28687818/26285379/d7da3656-3e4e-11e7-84ea-9db7f7171f01.png)

**Comment by Slowerzs** [comment] 2017-05-21 16:00
By the way, I do have he sound of he video with uBlock, not the video

**Comment by jspenguin2017** [comment] 2017-05-21 16:30
I see. I think the video player is replaced by something... I'll have a look.

**Comment by jspenguin2017** [comment] 2017-05-21 16:58
OK, there is a filter conflict with https://github.com/jspenguin2017/AdBlockProtector/issues/163
I'll make an exception.

**Comment by jspenguin2017** [comment] 2017-05-21 17:02
This should work now.

**Comment by Slowerzs** [comment] 2017-05-21 17:05
Perfect !

**Comment by uBlock-user** [comment] 2017-05-21 17:06
That will introduce the stitched ads, that's why you placed that filter in the first place.

**Comment by jspenguin2017** [comment] 2017-05-21 17:11
@uBlock-user Eh... So we have to replace the player then... 
@Slowerzs Does it cause ads reinsertion?

**Comment by uBlock-user** [comment] 2017-05-21 17:17
Actually, you only need the XHRs not Media to watch the video and on my end only XHRs sent which are not blocked. Something is blocking the XHRs on his end as with uBO I can play the video.

**Comment by uBlock-user** [comment] 2017-05-21 17:19
To see for yourself, open the logger and refresh the page, put `media` in the search filter and check if you can find any requests that are `media` in category.

**Comment by jspenguin2017** [comment] 2017-05-21 17:23
@uBlock-user That's not the case for me: 
![image](https://cloud.githubusercontent.com/assets/7283682/26285997/f4524f94-3e17-11e7-98d3-334ab5004cc6.png)

**Comment by uBlock-user** [comment] 2017-05-21 17:37
Hmmm,  not on my end

![](https://i.gyazo.com/8b766069c7d8aaf89b9b4812c5424feb.png)

**Comment by jspenguin2017** [comment] 2017-05-21 17:43
@uBlock-user Can you try again in incognito mode?

**Comment by uBlock-user** [comment] 2017-05-21 18:04
Same as usual

![](https://i.gyazo.com/36dd03e9bcd65042832e8af26d24daa0.png)

FYI, videos are Geo-Locked. I changed IP address to see it if happens and the video won't play it for me, so since the ads played are stitched to the video, they're also geo-locked.

**Comment by jspenguin2017** [comment] 2017-05-21 18:05
I figured out what is requesting that garbage... Patched in Script...

**Comment by jspenguin2017** [comment] 2017-05-21 18:08
![image](https://cloud.githubusercontent.com/assets/7283682/26286266/38240504-3e1e-11e7-8aa6-dcbb33feb758.png)

**Comment by jspenguin2017** [comment] 2017-05-23 16:50
Looks like it's still working. Closing.

**Closed by jspenguin2017** 2017-05-23 16:50 UTC
Labels: Fixed
